config/routes.rb
Rails.application.routes.draw do
  get 'debate/index'

  get 'debate/show' 

  devise_for :users
  root 'homes#show'
  resources :posts do 
    resources :comments
  end 
  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create, :show, :destroy, :update]
  resource :relationships, only: [:create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	if :name == nil 
		"annon" 
	end 
  validates :body, presence: true, length: {minimum: 5, maximum: 120}
  belongs_to :post
  belongs_to :user
end

app/models/debate.rb
class Debate < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 1, maximum: 80}
	validates :body, presence: true, length: {minimum: 5, maximum: 5000}
	validates :tags, presence: true
	validates :user_id, presence: true
	belongs_to :user
	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	has_many :comments, dependent: :destroy
	has_many :dabates, dependent: :destroy

	delegate :username, to: :user


	def all_tags=(names)
		self.tags = names.split(',').map do |name|
			Tag.where(name: name).first_or_create!
		end
	end

	def all_tags
		tags.map(&:name).join(',')
	end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :follwed, class_name: "User"

	validates :follower_id, presence: true
	validates :follwed_id, presence: true 
	
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings, dependent: :destroy 
	has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy

  has_many :passive_relationships, class_name: "Relationship",
  foreign_key: "follwed_id",
  dependent: :destroy

  has_many :followers, through: :passive_relationships, source: :follower

  has_many :active_relationships, class_name: "Relationship",
  foreign_key: "follower_id",
  dependent: :destroy

  has_many :followings, through: :active_relationships, source: :followed
  has_many :debates, dependent: :destroy
  def follow(other_user)
  	active_relationships.create(follwed_id: other_user.id)
  end

  def unfollow(other_user)
  	active_relationships.find_by(follwed_id: other_user.id).destroy
  end

  def following?(other_user)
  	following_ids.include?(other_user.id)
  end

  validates :username, presence: true

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def current_user?(user)
    current_user.id == user.id 
  end 

  helper_method :current_user?

   protected 
   	
   	def configure_permitted_parameters
   		devise_parameter_sanitizer.permit(:sign_up){ |u| u.permit(:username, :first_name, :last_name, :email, :password, :password_confirmation, :remember_me)}
   		devise_parameter_sanitizer.permit(:sign_in){|u| u.permit(:login, :username, :email, :password, :remember_me)}
   		devise_parameter_sanitizer.permit(:account_update){|u| u.permit(:username,:email, :password, :password_confirmation, :current_password)}
   	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authenticate_user!, only: [:create, :edit, :update, :destroy]
	def comments 
		@comments = Comment.order(created_at: :desc)
	end
	def create
		
		@post = Post.find(params[:post_id]) 
		@comments = @post.comments.create(params[:comment].permit(:name, :body))
		redirect_to post_path(@post)
	end
end

app/controllers/debate_controller.rb
class DebateController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def show
		@posts = Post.order(created_at: :desc)

	end
end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	def posts
		@posts = Post.order(created_at: :desc)
	end


	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.new(post_params)
		if @post.save
		redirect_to post_path(@post)
		else
			render :new
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
	  @post = Post.find(params[:id])
	  if @post.update(params[:post].permit(:title, :body, :tags))
	  	redirect_to @post
	  else
	  	render 'edit'
	end
end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path
	end

	private
	def post_params
		params.require(:post).permit(:title, :body, :all_tags)
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController  < ApplicationController 
	before_action :authenticate_user! 
	before_action :set_user

	def create 
		
		current_user.follow(@user)
		redirect_to @user
	end

	def destroy 
		
		current_user.unfollow(@user)
		redirect_to @user 
	end 

	private

	def set_user 
		@user =User.find(params[:user_id])
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:edit, :update]
	before_action :check_authorization, only: [:edit, :update] 
	before_action :set_user
	def show 
		
	end

	def edit 

	end

	def update 
		if @user.update!(user_params)
			redirect_to @user 
		else 
			flash.now[:alert] = "Something went wrong. Please try again."
			render :edit 
		end
	end

	private 

	def check_authorization
		unless current_user.id == params[:id].to_i
			redirect_to root_url 
		end 
	end

	def set_user 
		@user = User.find(params[:id])
	end

	def user_params 
		params.require(:user).permit(:username, :avatar, :description, :userurl)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/debate_helper.rb
module DebateHelper
end

app/helpers/users_helper.rb
module UsersHelper 
	def avatar_for(user, options = {size: 80})
		size = options[:size]
		if user.avatar? 
			image_tag user.avatar.url(:thumb), width: size, class: "avatar-image"
		else
			image_tag "profile_default.jpg", width: size, class: "avatar-image"
		end
	end
end

app/views/comments/_comment.html.erb
<p>comment by: <%= comment.name %></p><p><%= time_ago_in_words(comment.created_at)%> ago</p> 
<p><%= comment.body %></p>
<br>

app/views/comments/_form.html.erb
<%= form_for ([@post,@post.comments.build]) do |f| %>
  
  <% if !user_signed_in? %>
    <%= f.label :name == current_user.username %>
  <% else %>  
    <%= f.text_field :name, placeholder: "name" %>
  <%end%>
  	
  	 <br>

  	<p>
  		<%= f.text_area :body, placeholder: "write a comment" %>
  	</p>
  	 <br>
  	<p>
  		<%= f.submit %>
  	</p>
  <%end %>

app/views/debate/index.html.erb
<h1>Debate#index</h1>
<p>Find me in app/views/debate/index.html.erb</p>

app/views/debate/show.html.erb
<%= stylesheet_link_tag "debate_show.css" %>

<h1 style = "text-align: center;">Debate</h1>
<h6 style = "text-align: center;">Tim and Steve</h6>
<div class = "original-post">
  <div class="post-title">
   Tim Cook is lowkey runining my legecy
  </div>
  <p style = "font-size: 14px;">by steve</p>
  <p style = "font-size: 11px;">submitted an hour ago</p>
  <p class="show_body">Ever since Tim Cook took over the reigns of power at my beloved Apple, he has been steadily eroding my legacy. Its high time some kicks him to the curp before he completely ruins what I worked so hard to build. Enough is enough. I mean come on people what the fuck is up with the iPad Pro? there is nothing "Pro" about it. its just a big ipad with a pencil that no one wants or needs. And what about the new magic mouse? You have to flip the thing over to charge it, making it unuseable while its being charged. He seems to be more worried about social issues and wheather Apple is "diverise"  enough then actully making great products people want and love. Who cares about diveristy if your products suck!? The crazy ones have left Apple, and it is Tims fault.</p>
  <a style = 'font-size: 11px;' href="debate/show">edit</a> <a style = 'font-size: 11px;' href="debate/show">delete</a>
</div>

<div class = "response-post">
  <div class="post-title">
  Apple is a better company because of me, So Shut up Steve!
  </div>
  <p style = "font-size: 14px;">in reply to: Tim Cook is lowkey runining my legecy by steve</p>
  <p style = "font-size: 11px;">submitted an hour ago</p>

  <p class="show_body">You know nothing Steve Jobs! Since I took over, Apple revenue has jumped nearly 10% year over year. Our stock prices have never been higher, and we now give to many charities </p>
  <!-- <a style = 'font-size: 11px;' href="debate/show">edit</a> <a style = 'font-size: 11px;' href="debate/show">delete</a> -->

  <a style = 'font-size: 12px;' href="debate/show">Respond</a>
</div>

app/views/homes/show.html.erb
<div class= "col-md-6 col-md-offset-1">

<div class= "posts">
	<%= render @posts %>
	
</div>
</div>

app/views/layouts/_header.html.erb
<% if !user_signed_in? %>
  <%= render '/layouts/header_guest' %>
<% else %> 
  <%= render '/layouts/header_user' %> 
<%end%>

app/views/layouts/_header_guest.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
   <%= link_to "OpEd", root_path, class: "navbar-brand" %>
   <ul class="nav navbar-nav navbar-right">
	    <li class= "new-opinion-button"><%= link_to "Share your opinion", new_post_path, class: "button" %></li>
	    <li class = "sign-in"><%= link_to "Sign in / Sign up", new_user_session_path, class: "button" %> </li>
	</ul>
	</div>
</nav>

app/views/layouts/_header_user.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
   <%= link_to "OpEd", root_path, class: "navbar-brand" %>
   <ul class="nav navbar-nav navbar-right">
	<li class= "new-opinion-button"><%= link_to "Share your opinion", new_post_path, class: "button" %></li>
	<li class="dropdown">
         <li class="current-user-avatar"><%= link_to(avatar_for(current_user, size: 25), current_user, class:"current-user-avatar") %></li>
          <ul class="dropdown-menu">
            <li><a href="users/<%=current_user.username%>">profile</a></li>
            <li><a href="#">help</a></li>
            <li><%=link_to('edit profile', edit_user_registration_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%=link_to('sign out', destroy_user_session_path, :method => :delete)%></li>
	</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpEd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
</head>
<body>
<%= render "layouts/header" %>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<div class= "container">
	<%= yield %>
</div>


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<% if @post.errors.any? %>
<div class= "error">
<h2>
    <%= pluralize(@post.errors.count, "error") %> prevented this post from being saved:
</h2>
<ul>
    <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
    </ul>
</div>
<%end%>
<div class="form-group">
<%= f.label  :title %>
<%= f.text_field :title, autofocus: true, class: "form-control" %> 
</div>

<div class="form-group">
<%= f.label :body %>
<%= f.text_area :body, class: "form-control" %>
</div>

<div class="form-group">
<%= f.label :tags %>
<%= f.text_field :all_tags, class: "form-control" %>
</div>

<%= f.submit "Publish", class: "btn btn-primary" %>
<% end %>

app/views/posts/_post.html.erb
<%= stylesheet_link_tag "post_page.css" %>

<div class="row">
	<div class="col-xs-1">
	</div>
    <div class="col-xs-10">
    <div class="panel panel-default">
			<h3 class = 'post-title'><%=link_to post.title, post, style: 'color:black' %></h3>

    	<p style = 'font-size: 12px;'><%= link_to(avatar_for(post.user, size: 20), current_user) %>
		<%= link_to post.username, post.user %>  <%= time_ago_in_words(post.created_at)%> ago</p>

		<div><%= truncate_html(post.body.html_safe, length: 80) %>
           <div style = 'font-size: 11px'>
						 <%= link_to "Read More..", post %>
					 </div>
        </div>
				<br />
				<div style = "margin-bottom: 10px;">
						<a style = 'font-size: 12px;' href="debate/show">(1 Debate)</a>
				</div>
				        <!-- <p class="comments">comments(<%= link_to post.comments.count, post %>)</p> -->
		<p style = 'font-size: 11px;'>tags: <%= post.all_tags%></p>
    </div>
    </div>
    <div class="col-xs-1">
  </div>
</div>

app/views/posts/edit.html.erb
<div id="row">
<div id="col-md-6 col-md-offset-3">
<center><h1>edit</h1></center>

<%= render "form" %>
</div>
</div>

app/views/posts/new.html.erb
<div id="row">
<div id="col-md-6 col-md-offset-3">
<center><h1>share your opinion</h1></center>
<%= render "form" %>
</div>
</div>

app/views/posts/show.html.erb
<h1 class="show_title">
<%=@post.title%>
</h1>
<p class="show_date">submitted <%= time_ago_in_words(@post.created_at)%> ago</p>
<p class="show_body"><%=@post.body.html_safe%></p>
<p class="show_options"><%= link_to "edit", post_path(@post), method: :edit%> <%= link_to "delete", post_path(@post), method: :delete, data: {confirm: "Are you sure"}%></p>
<a style = 'font-size: 16px;' href="debate/show">(1) debate</a>
<br>
<h4 style = "margin-top: 20px; font-size: 16px;">
	(<%= @post.comments.count %>) comments
</h4>
<div style = "border: 1px solid #e8e8e8; border-radius: 5px; padding: 5px;">
	<%= render @post.comments %>
</div>

	<%= render "comments/form" %>

app/views/users/edit.html.erb
<%= stylesheet_link_tag "user_profile.css" %>

<h1>Edit profile</h1>

<%= form_for(@user, html: {mulipart: true}) do |f| %>

<div class = "edit-item-title">
  <%= f.label :username %>
</div>
<div class = "edit-item-text-field">
  <%= f.text_field :username %>
</div>

<div class = "edit-item-title">
  <%= f.label :url %>
</div>
<div class = "edit-item-text-field">
  <%= f.text_field :userurl %>
</div>

<div class = "edit-item-title">
  <%= f.label :email %>
</div>
<div class = "edit-item-text-field">
  <%= f.text_field :email %>
</div>

<div class = "edit-item-title">
  <%= f.label :bio %>
</div>
<div class = "edit-item-text-field">
  <%= f.text_area :description, placeholder: "Write something about yourself." %>
</div>

<div class = "edit-item-title">
  <%= f.label :photo %>
</div>
<div class = "edit-item-text-field">
  <%= f.file_field :avatar %>
</div>

<br>

<%= f.submit "Save changes" %>

<%end%>

app/views/users/show.html.erb
<%= stylesheet_link_tag "user_profile.css" %>

<div class = "user-profile">
	<h1><%= avatar_for(@user, size: 40)%> <%= @user.username %></h1>

	<div>
		<% if user_signed_in? != current_user?(@user) %>
		<% if current_user.following?(@user)%>
		<%= button_to "Unfollow", relationships_path(user_id: @user.id),
		method: :delete, class: "button" %>
		<%else%>
		<%= button_to "Follow", relationships_path(user_id: @user.id),
		class: "button" %>
		<%end%>
		<%end%>
	</div>

	<div class = "profile-description">
		website:
	</div>
	<div class = "description-text">
		<%= link_to @user.userurl %>
	</div>

	<br>

	<div class = "profile-description">
		email:
	</div>
	<div class = "description-text">
		<%= @user.email %>
	</div>

	<br>

	<div class = "profile-description">
		bio:
	</div>
	<div class = "description-text">
		<%= @user.description %>
	</div>

	<br>
	<br>

	<!-- Edit profile & Logout -->
	<% if user_signed_in? && current_user?(@user) %>
	<%= link_to "Edit Profile", edit_user_path(@user)%>
	<%end%>

	<br>

	<% if user_signed_in? && current_user?(@user) %>
	<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
	<%end%>

</div>